### ISSUE TITLE
Text-Lines

### ISSUE THREAD

**Issue by seekingdeep** [Actasidiot/EFIFSTR#5]
@Actasidiot 
- is EFIFSTR capable of training and recognizing text-lines instead of using words?
- is it limited to English, or can it be trained on other languages such as Arabic and Hebrew?

**Comment by Actasidiot** [comment]
(1) EFIFSTR is an **attention-based** model so it might not work well in a long text line whose length > 15 (due to **the attention shift problem**).  A possible way is to split the text line first and then send segments into our model.
(2) It can be applied into language systems where **we can exactly locate each single character from a word (or text line)**. So I think it can be applied to Arabic and Hebrew. In this paper we aim to explore the font-invariant features, so you need to collect a wide range of Arabic and Hebrew fonts (render the glyph images) for our model to learn.

**Comment by seekingdeep** [comment]
Arabic and Hebrew are a bit like cursive writing, inwhich the letters are linked together to form the words. So it might be a dilemma.
Thanks
